#!/bin/sh
echo "         Schedd    Job    Job    Current Historical    Current Historical"
echo "                Starts  Compl   Runtimes   Runtimes   Idletime   Idletime"
echo "                  /sec   /sec      (sec)      (sec)      (sec)      (sec)"
echo
condor_status -constraint 'TotalRunningJobs>0 && MeanRunningTime<900 && MeanRunningTime>0' -schedd -format '%15.15s ' Name -format '%6.2f ' JobStartRate -format '%6.2f ' JobCompletionRate -format '%10.1f ' MeanRunningTime -format '%10.1f ' MeanRunningTimeCum -format '%10.1f ' MeanTimeToStart -format '%10.1f\n' MeanTimeToStartCum

